basic_app/urls.py
from django.conf.urls import url
from basic_app import views 

# TEMPLATE URLS
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register')
]

signup_screen/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls'))
]

basic_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

GENDER = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE'),
)

# Create your models here.
class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User)

    gender = models.CharField(max_length=128, choices=GENDER, default='FEMALE')
    age = models.IntegerField(validators=[MinValueValidator(16),
                                       MaxValueValidator(100)])

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User 
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ("username","first_name","last_name","email","password")


class UserProfileInfoForm(forms.ModelForm):
    """Form definition for UserProfileInfo."""

    class Meta:
        """Meta definition for UserProfileInfoform."""

        model = UserProfileInfo
        fields = ('gender','age')

basic_app/views.py
from basic_app.forms import UserForm, UserProfileInfoForm
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
                
            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sign Up</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand" href="{% url 'index'}">Achim</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Sign Up</a>
                 </li>
            </ul>
        </div>
    </nav>
    <br>

    <div class="container">
        {% block body %}
        {% endblock body %}
    </div>
    
           
</body>
</html>

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}


{% block body %}

<div class="jumbotron">
    <h1>Achim Sign Up</h1>
</div>
    
{% endblock %}
    

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}

{% block body %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register here!</h1>
            <h3>Fill out the Form:</h3>

            <form enctype="multipart/form-data" method="POST"  action="">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input class="waves-effect waves-light btn" type="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock body %} 